version: '3.8'

services:
  forensic-analyzer:
    build: .
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./logs:/app/logs
      - ./rules:/app/rules
    tty: true
    stdin_open: true

volumes:
  clamav-data:
    driver: local 
