version: '3.8'

services:
  forensic-analyzer:
    build: .
    container_name: forensic-analyzer
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./logs:/app/logs
      - ./rules:/app/rules
      - clamav-data:/var/lib/clamav
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    ports:
      - "3310:3310"
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3310"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: "no"

volumes:
  clamav-data:
    driver: local 